[project]
name = "utils"
version = "0.1.0"
dependencies = [
    "pyyaml>=6.0",
    "multipledispatch>=0.6.0",
    "pandas",
    "tqdm",
]
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[tool.hatch.build.targets.wheel]
packages = ["utils"]